---
ignoredBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
  - register-scheme

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
